### ISSUE TITLE
Create a lower speed TF536 debug firmware

### ISSUE THREAD

**Issue by modulatix** [terriblefire/terriblefire-binaries#1]
Hello, this a feature request:
Please create a version of firmware for TF536 that divides crystal generator clock for CPU by factor of, for example, 4.
The point here is to differentiate issues by testing will 68030 work on 25MHz to understand is Chinese remark an issue or it is another hardware failure. Debug firmware of sorts.

**Comment by terriblefire** [comment]
Sorry but  this is a huge amount of work. I tried this already and i gave up. 

The issue is the code assumes relative timing with the SDRAM. 

If you just run code in chip/rom the cpu runs at 7Mhz.

**Comment by modulatix** [comment]
Thank you, yes, I've forgot about SDRAM timings, my bad
